### ISSUE TITLE
CPANTS web site defacement

### ISSUE THREAD

**Issue by mperry2** [cpants/www-cpants#38]
It looks like part of the CPANTS site has been defaced. I went to http://cpants.cpanauthors.org/dist/App-ClusterSSH and got the page in the screenshot below. I didn't click around on anything else to see the extent of the damage as I don't want to compromise my computer.

![cpants hacked page](https://f.cloud.github.com/assets/2487505/1829341/f9de4f4c-72a2-11e3-89dc-8d81a2746e74.png)

**Comment by dolmen** [comment]
This is fixed.

**Comment by charsbar** [comment]
@dolmen, stop saying "fixed" until you write a test to ensure the same thing would not happen again.

**Comment by dolmen** [comment]
@charsbar Considering that the title of this issue is quite misleading (AFAIK cpants has never been hacked) I think it would be better to close this issue as there is no more problem for the particular URL reported.

If you are concerned about losing reports about broken links leading to 404 pages, I think it would be better to have a separate issue. Because an automated way of collecting 404 issues would be better than relying on manual reports.

**Comment by charsbar** [comment]
@dolmen, I believe you can't tell me what was the "something weird" and how you (or I) have "fixed" it. It's not the matter of looking ok at some point. This issue still has several good reasons to be kept open. It's ok for you to open another issue for what you think you find in this ticket, but as I said, just don't say "fixed" for what you don't even understand.
